navbar:
  blog_title: muse
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/1616421669417-wallhaven-1kkm2g.jpg
  banner_img_height: 100
  slogan:
    text: 平步云端
post:
  banner_img: /images/uploads/40ff251e2a5c4764b2f59513fbdd8c81.webp
  banner_img_height: 70
  default_index_img: /images/uploads/40ff251e2a5c4764b2f59513fbdd8c81.webp
archive:
  banner_img: /images/uploads/1616421595370-wallhaven-q6ov7d.jpg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: /images/uploads/1616421818281-wallhaven-zm93dj.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: /images/uploads/1616421669417-wallhaven-1kkm2g.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/wallhaven-pkkr2.webp
  banner_img_height: 80
  subtitle: null
  avatar: /img/avatar.png
  name: muse
  intro: 没有介绍哦
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items: []
